// ─────────────────────────────────────────────
//  Cascade AI — Media generation tools
// ─────────────────────────────────────────────
//
//  Tools are only registered for modalities the account can ACTUALLY serve
//  (see MultimodalRegistry.usable). A tool that exists but always fails is
//  worse than an absent one: the planner writes steps around it, the worker
//  burns a call discovering it doesn't work, and the run ends in an apology —
//  the same shape as the dead-model problem the run breaker was built for.
//
//  Generated bytes are handed to a sink supplied by the host (desktop writes to
//  disk, cloud stores a file row). The tools themselves never touch the
//  filesystem, so they behave identically in both, and a cloud worker with no
//  disk tools can still produce an image.

import type { ToolExecuteOptions, ProviderConfig } from '../types.js';
import { BaseTool } from './base.js';
import type {
  GenerationCapability,
  GenerationModality,
  MultimodalRegistry,
  SelectionResult,
} from '../core/multimodal/registry.js';
import { classifyProviderError } from '../core/router/provider-errors.js';
import {
  generateImage,
  generateSpeech,
  generateVideo,
  transcribeAudio,
  type GeneratedAsset,
} from '../core/multimodal/generate.js';

/**
 * Where finished bytes go. Returns a short human-readable locator (a path, a
 * file id, a URL) that the tool reports back to the model.
 */
export type AssetSink = (asset: GeneratedAsset) => Promise<string>;

/** Resolves the provider config (and key) for a capability's provider. */
export type ProviderConfigLookup = (provider: string) => ProviderConfig | undefined;

interface Deps {
  registry: MultimodalRegistry;
  sink: AssetSink;
  lookupProvider: ProviderConfigLookup;
}

type Resolved =
  | { ok: false; error: string }
  | { ok: true; selected: NonNullable<ReturnType<MultimodalRegistry['select']>>; cfg: ProviderConfig };

/** Shared: resolve capability + config, or explain precisely what's missing. */
function resolve(
  deps: Deps,
  modality: 'image' | 'speech' | 'transcription' | 'video',
  preferModel?: string,
): Resolved {
  const selected = deps.registry.select(modality, preferModel ? { preferModel } : {});
  if (!selected) {
    return { ok: false, error: `No ${modality} model is available on your configured providers.` };
  }
  const cfg = deps.lookupProvider(selected.capability.provider);
  if (!cfg) {
    return {
      ok: false,
      error: `${selected.capability.modelId} needs the ${selected.capability.provider} provider, which is not configured.`,
    };
  }
  return { ok: true, selected, cfg };
}

function messageOf(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}

/** A finished generation, plus what it cost in attempts to get there. */
interface Attempt<T> {
  value: T;
  /** The capability that actually produced `value`. */
  selected: SelectionResult;
  /** Set only when the first choice failed systemically and this is the retry. */
  fellBackFrom?: { capability: GenerationCapability; error: string };
}

/**
 * Run a generation, and on a SYSTEMIC failure retry it against a different
 * provider that can serve the same modality.
 *
 * Why this exists: classifyProviderError answers "would this fail again on the
 * SAME provider+model?" — a dead key, a 404 model id, an exhausted quota. The
 * T3 worker reads that answer as "the whole capability is gone" and fast-fails
 * the worker with a CriticalToolError. That is right once, but it was being
 * applied while a second configured provider sat there able to draw the
 * picture: Gemini's image endpoint 404ing says nothing about whether OpenAI's
 * dall-e-3 works. So the exhaustion has to be established HERE, where the
 * alternatives are known, before the worker is told the capability is dead.
 *
 * Deliberately NOT retried:
 *   • non-systemic failures (content-policy refusal, malformed prompt, a
 *     transport blip) — those would very plausibly fail the same way on the
 *     next provider, so a second call buys latency and cost and nothing else;
 *   • a cancelled run — the user already said stop.
 *
 * One attempt per ALTERNATE PROVIDER, in registry rank order. A second model
 * from the same provider is skipped because the failures this retries on are
 * account-scoped (auth, quota) or rate-limit-scoped far more often than they
 * are model-scoped, so it would usually just buy the same error twice.
 */
async function runWithProviderFallback<T>(
  deps: Deps,
  modality: GenerationModality,
  first: { selected: SelectionResult; cfg: ProviderConfig },
  run: (cap: GenerationCapability, cfg: ProviderConfig) => Promise<T>,
  signal?: AbortSignal,
): Promise<Attempt<T>> {
  const failed = first.selected.capability;
  try {
    return { value: await run(failed, first.cfg), selected: first.selected };
  } catch (err) {
    if (signal?.aborted || !classifyProviderError(err).systemic) throw err;

    const tried = [`${failed.modelId} (${failed.provider}): ${messageOf(err)}`];
    let allSystemic = true; // the primary was systemic, by construction
    let lastNonSystemic: unknown; // set when a fallback fails for a reason unrelated to provider health
    const seen = new Set<string>([failed.provider]);

    for (const alt of deps.registry.rank(modality)) {
      if (seen.has(alt.capability.provider)) continue;
      // Mirrors resolve()'s own check: a capability whose provider carries no
      // config is not a fallback, it is a second way to fail.
      const cfg = deps.lookupProvider(alt.capability.provider);
      if (!cfg) continue;
      seen.add(alt.capability.provider);
      try {
        return {
          value: await run(alt.capability, cfg),
          selected: alt,
          fellBackFrom: { capability: failed, error: messageOf(err) },
        };
      } catch (retryErr) {
        if (signal?.aborted) throw retryErr;
        tried.push(`${alt.capability.modelId} (${alt.capability.provider}): ${messageOf(retryErr)}`);
        if (classifyProviderError(retryErr).systemic) {
          continue;
        }
        allSystemic = false;
        lastNonSystemic = retryErr;
      }
    }

    // Nothing to fall back to — propagate the original error untouched, so a
    // single-provider account behaves exactly as it did before.
    if (tried.length === 1) throw err;

    // A fallback failed for a reason unrelated to provider health (a content
    // refusal, a malformed prompt) rather than the primary's kind of systemic
    // failure. Propagate THAT error on its own, not merged into the combined
    // "every provider failed" message below — t3-worker.ts re-runs
    // classifyProviderError() on whatever this throws (PROVIDER_BACKED_TOOLS
    // are always re-classified, regardless of any `systemic` tag we do or
    // don't set), and its text matcher works over the WHOLE message. A
    // concatenated string still carrying the primary's systemic wording (e.g.
    // "model not found") gets matched by that same regex and fast-fails the
    // worker even though the actual, deciding failure — the fallback's — was
    // never systemic at all.
    if (!allSystemic) throw lastNonSystemic;

    // Every configured provider is exhausted, so the worker's fast-fail is now
    // the correct response. Naming each provider matters: "it failed" reads as
    // a blip worth retrying, "both providers failed, here is what each said"
    // reads as the configuration problem it actually is. The `systemic` tag is
    // the same one web_search uses to mark its own failure unrecoverable — it
    // makes the escalation deterministic instead of leaving t3-worker to
    // re-derive it from prose.
    const exhausted = new Error(
      `${modality} generation failed on every configured provider (${seen.size} tried). ${tried.join(' ')}`,
    );
    Object.assign(exhausted, { systemic: true });
    throw exhausted;
  }
}

// ── Image ─────────────────────────────────────

export class GenerateImageTool extends BaseTool {
  readonly name = 'generate_image';
  readonly description =
    'Generate an image from a text description using the best available image model. Returns where the image was saved. Use when the user asks for a picture, illustration, diagram render, logo or any visual asset.';
  readonly inputSchema = {
    type: 'object',
    properties: {
      prompt: { type: 'string', description: 'What the image should show. Be specific about subject, style and composition.' },
      size: { type: 'string', description: 'Pixel size, e.g. "1024x1024" (default), "1792x1024", "1024x1792".' },
      model: { type: 'string', description: 'Optional: force a specific image model instead of the automatic choice.' },
    },
    required: ['prompt'],
  };

  constructor(private deps: Deps) { super(); }

  async execute(input: Record<string, unknown>, options: ToolExecuteOptions): Promise<string> {
    const prompt = String(input['prompt'] ?? '').trim();
    if (!prompt) return 'Provide a "prompt" describing the image.';

    const r = resolve(this.deps, 'image', input['model'] ? String(input['model']) : undefined);
    if (!r.ok) return r.error;

    const size = input['size'] ? String(input['size']) : undefined;
    // Image is the one modality with two providers in the catalogue today
    // (dall-e-3 on OpenAI, gemini-2.5-flash-image on Gemini), so it is the one
    // where a systemic failure is worth a second opinion. Speech is two OpenAI
    // models — one dead key kills both — and video and transcription have a
    // single capability each, so there is nothing to fall back TO. When a
    // second provider lands for any of them, the change is to route that call
    // through runWithProviderFallback the same way.
    const attempt = await runWithProviderFallback(
      this.deps, 'image', r,
      (cap, cfg) => generateImage(cap, cfg, { prompt, ...(size ? { size } : {}) }, options.signal),
      options.signal,
    );
    const asset = attempt.value;
    const fell = attempt.fellBackFrom;
    const location = await this.deps.sink(asset);

    return [
      `Image generated and saved to ${location}.`,
      // Knowing WHERE the image is isn't the same as knowing how to use it: a
      // model told only "saved to X" tends to describe the picture in prose
      // instead of embedding it. Spelling out the reference syntax here makes
      // the worker's "never write a placeholder" rule concretely actionable,
      // and it works for every host because `location` is whatever that host's
      // sink returned — a workspace path on desktop/CLI, a URL in the cloud.
      `To include this image in your output, reference it as: ![description](${location})`,
      // The reported model has to be the one that actually drew the picture, not
      // the one that was picked and then failed.
      `Model: ${asset.modelId} — ${fell
        ? `used as a fallback after ${fell.capability.modelId} (${fell.capability.provider}) failed with a systemic error.`
        : attempt.selected.reason}`,
      // Worth one line: the run succeeded, so nothing else will report that a
      // configured provider is broken, and "your Gemini key is dead" is exactly
      // the kind of thing the user wants to hear once rather than never.
      fell ? `Note: ${fell.capability.provider} failed first — ${fell.error}` : '',
      // DALL·E rewrites the prompt before drawing; the model needs to know what
      // was actually rendered, not what it asked for, or its description of the
      // result will not match the image.
      asset.revisedPrompt ? `The provider rewrote the prompt to: ${asset.revisedPrompt}` : '',
    ].filter(Boolean).join('\n');
  }
}

// ── Speech ────────────────────────────────────

export class GenerateSpeechTool extends BaseTool {
  readonly name = 'generate_speech';
  readonly description =
    'Turn text into spoken audio using the best available text-to-speech model. Returns where the audio was saved. Use when the user asks for narration, a voiceover or an audio version of some text.';
  readonly inputSchema = {
    type: 'object',
    properties: {
      text: { type: 'string', description: 'The text to speak.' },
      voice: { type: 'string', description: 'Voice id: alloy, echo, fable, onyx, nova, shimmer. Default alloy.' },
      format: { type: 'string', description: 'Audio format: mp3 (default), opus, aac, flac, wav.' },
      model: { type: 'string', description: 'Optional: force a specific speech model.' },
    },
    required: ['text'],
  };

  constructor(private deps: Deps) { super(); }

  async execute(input: Record<string, unknown>, options: ToolExecuteOptions): Promise<string> {
    const text = String(input['text'] ?? '').trim();
    if (!text) return 'Provide "text" to speak.';

    const r = resolve(this.deps, 'speech', input['model'] ? String(input['model']) : undefined);
    if (!r.ok) return r.error;

    const fmt = String(input['format'] ?? 'mp3');
    const allowed = ['mp3', 'opus', 'aac', 'flac', 'wav'] as const;
    const format = (allowed as readonly string[]).includes(fmt)
      ? fmt as typeof allowed[number]
      : 'mp3';

    const asset = await generateSpeech(
      r.selected.capability, r.cfg,
      { text, voice: input['voice'] ? String(input['voice']) : undefined, format },
      options.signal,
    );
    const location = await this.deps.sink(asset);
    return `Speech generated and saved to ${location}.\nModel: ${asset.modelId} — ${r.selected.reason}`;
  }
}

// ── Video ─────────────────────────────────────

/** Clip length used when the caller doesn't say. Kept short — see the cost note. */
const DEFAULT_VIDEO_SECONDS = 5;
/** Hard ceiling regardless of what the model asks for. */
const MAX_VIDEO_SECONDS = 8;

export class GenerateVideoTool extends BaseTool {
  readonly name = 'generate_video';
  // The price is in the description on purpose. Video is ~1000x the cost of an
  // image per call, it is billed per SECOND, and the model choosing the
  // duration is the one deciding the bill — so the number has to be where the
  // model reads before calling, not only in the result afterwards.
  readonly description =
    'Generate a short video clip from a text description. EXPENSIVE and slow: billed per second of output (about $0.40/second, so a 5-second clip costs roughly $2) and takes 1-3 minutes. Only use when the user explicitly asks for a video, and prefer the shortest duration that satisfies the request.';
  readonly inputSchema = {
    type: 'object',
    properties: {
      prompt: { type: 'string', description: 'What the video should show: subject, action, camera movement, style.' },
      seconds: { type: 'number', description: `Clip length, 1-${MAX_VIDEO_SECONDS} seconds (default ${DEFAULT_VIDEO_SECONDS}). Billed per second — keep it short.` },
      aspectRatio: { type: 'string', description: 'Frame shape: "16:9" (default) or "9:16" for vertical.' },
      model: { type: 'string', description: 'Optional: force a specific video model.' },
    },
    required: ['prompt'],
  };

  constructor(private deps: Deps) { super(); }

  async execute(input: Record<string, unknown>, options: ToolExecuteOptions): Promise<string> {
    const prompt = String(input['prompt'] ?? '').trim();
    if (!prompt) return 'Provide a "prompt" describing the video.';

    const r = resolve(this.deps, 'video', input['model'] ? String(input['model']) : undefined);
    if (!r.ok) return r.error;

    // Clamp rather than reject: a model asking for 30 seconds has misjudged the
    // cost, and silently spending $12 to teach it that would be the wrong
    // lesson to charge the user for.
    const asked = typeof input['seconds'] === 'number' ? input['seconds'] : DEFAULT_VIDEO_SECONDS;
    const seconds = Math.max(1, Math.min(MAX_VIDEO_SECONDS, Math.round(asked)));

    const asset = await generateVideo(
      r.selected.capability, r.cfg,
      {
        prompt,
        seconds,
        ...(input['aspectRatio'] ? { aspectRatio: String(input['aspectRatio']) } : {}),
      },
      options.signal,
      // Progress goes to the run log so a two-minute wait doesn't look like a
      // hang — the single most likely reason someone kills a working render.
      (note) => options.onProgress?.(note),
    );
    const location = await this.deps.sink(asset);

    const unit = r.selected.cost;
    const estimate = unit ? ` Estimated cost: $${(unit.amount * seconds).toFixed(2)} (${seconds}s x ${unit.label}).` : '';
    const clamped = seconds !== Math.round(asked) ? ` Duration was clamped to ${seconds}s (max ${MAX_VIDEO_SECONDS}).` : '';
    return `Video generated and saved to ${location}.\nModel: ${asset.modelId}.${estimate}${clamped}`;
  }
}

// ── Transcription ─────────────────────────────

export class TranscribeAudioTool extends BaseTool {
  readonly name = 'transcribe_audio';
  readonly description =
    'Transcribe a local audio file to text using the best available speech-to-text model. Use when the user supplies audio and wants its contents in writing.';
  readonly inputSchema = {
    type: 'object',
    properties: {
      path: { type: 'string', description: 'Path to the audio file to transcribe.' },
      language: { type: 'string', description: 'Optional ISO-639-1 language hint, e.g. "en", improves accuracy.' },
      model: { type: 'string', description: 'Optional: force a specific transcription model.' },
    },
    required: ['path'],
  };

  constructor(private deps: Deps, private readFile: (p: string) => Promise<Buffer>) { super(); }

  async execute(input: Record<string, unknown>, options: ToolExecuteOptions): Promise<string> {
    const filePath = String(input['path'] ?? '').trim();
    if (!filePath) return 'Provide a "path" to the audio file.';

    const r = resolve(this.deps, 'transcription', input['model'] ? String(input['model']) : undefined);
    if (!r.ok) return r.error;

    let audio: Buffer;
    try {
      audio = await this.readFile(filePath);
    } catch {
      return `Could not read the audio file at ${filePath}.`;
    }

    const { text, modelId } = await transcribeAudio(
      r.selected.capability, r.cfg,
      {
        audio,
        filename: filePath.split(/[\\/]/).pop() || 'audio',
        ...(input['language'] ? { language: String(input['language']) } : {}),
      },
      options.signal,
    );
    return text
      ? `Transcript (${modelId}):\n\n${text}`
      : `${modelId} returned an empty transcript — the file may be silent or in an unsupported format.`;
  }
}

/**
 * Build only the media tools this account can actually run.
 *
 * `transcribe_audio` additionally needs a file reader, so it is omitted on a
 * host with no filesystem (cloud) even when a transcription model exists —
 * there would be nothing for it to read.
 */
export function buildMediaTools(
  deps: Deps,
  readFile?: (p: string) => Promise<Buffer>,
): BaseTool[] {
  const tools: BaseTool[] = [];
  const modalities = new Set(deps.registry.availableModalities());
  if (modalities.has('image')) tools.push(new GenerateImageTool(deps));
  if (modalities.has('speech')) tools.push(new GenerateSpeechTool(deps));
  if (modalities.has('video')) tools.push(new GenerateVideoTool(deps));
  if (modalities.has('transcription') && readFile) tools.push(new TranscribeAudioTool(deps, readFile));
  return tools;
}
