// ─────────────────────────────────────────────
//  Cascade AI — Media generation tools
// ─────────────────────────────────────────────
//
//  Tools are only registered for modalities the account can ACTUALLY serve
//  (see MultimodalRegistry.usable). A tool that exists but always fails is
//  worse than an absent one: the planner writes steps around it, the worker
//  burns a call discovering it doesn't work, and the run ends in an apology —
//  the same shape as the dead-model problem the run breaker was built for.
//
//  Generated bytes are handed to a sink supplied by the host (desktop writes to
//  disk, cloud stores a file row). The tools themselves never touch the
//  filesystem, so they behave identically in both, and a cloud worker with no
//  disk tools can still produce an image.

import type { ToolExecuteOptions, ProviderConfig } from '../types.js';
import { BaseTool } from './base.js';
import type { MultimodalRegistry } from '../core/multimodal/registry.js';
import {
  generateImage,
  generateSpeech,
  generateVideo,
  transcribeAudio,
  type GeneratedAsset,
} from '../core/multimodal/generate.js';

/**
 * Where finished bytes go. Returns a short human-readable locator (a path, a
 * file id, a URL) that the tool reports back to the model.
 */
export type AssetSink = (asset: GeneratedAsset) => Promise<string>;

/** Resolves the provider config (and key) for a capability's provider. */
export type ProviderConfigLookup = (provider: string) => ProviderConfig | undefined;

interface Deps {
  registry: MultimodalRegistry;
  sink: AssetSink;
  lookupProvider: ProviderConfigLookup;
}

type Resolved =
  | { ok: false; error: string }
  | { ok: true; selected: NonNullable<ReturnType<MultimodalRegistry['select']>>; cfg: ProviderConfig };

/** Shared: resolve capability + config, or explain precisely what's missing. */
function resolve(
  deps: Deps,
  modality: 'image' | 'speech' | 'transcription' | 'video',
  preferModel?: string,
): Resolved {
  const selected = deps.registry.select(modality, preferModel ? { preferModel } : {});
  if (!selected) {
    return { ok: false, error: `No ${modality} model is available on your configured providers.` };
  }
  const cfg = deps.lookupProvider(selected.capability.provider);
  if (!cfg) {
    return {
      ok: false,
      error: `${selected.capability.modelId} needs the ${selected.capability.provider} provider, which is not configured.`,
    };
  }
  return { ok: true, selected, cfg };
}

// ── Image ─────────────────────────────────────

export class GenerateImageTool extends BaseTool {
  readonly name = 'generate_image';
  readonly description =
    'Generate an image from a text description using the best available image model. Returns where the image was saved. Use when the user asks for a picture, illustration, diagram render, logo or any visual asset.';
  readonly inputSchema = {
    type: 'object',
    properties: {
      prompt: { type: 'string', description: 'What the image should show. Be specific about subject, style and composition.' },
      size: { type: 'string', description: 'Pixel size, e.g. "1024x1024" (default), "1792x1024", "1024x1792".' },
      model: { type: 'string', description: 'Optional: force a specific image model instead of the automatic choice.' },
    },
    required: ['prompt'],
  };

  constructor(private deps: Deps) { super(); }

  async execute(input: Record<string, unknown>, options: ToolExecuteOptions): Promise<string> {
    const prompt = String(input['prompt'] ?? '').trim();
    if (!prompt) return 'Provide a "prompt" describing the image.';

    const r = resolve(this.deps, 'image', input['model'] ? String(input['model']) : undefined);
    if (!r.ok) return r.error;

    const size = input['size'] ? String(input['size']) : undefined;
    const asset = await generateImage(
      r.selected.capability, r.cfg,
      { prompt, ...(size ? { size } : {}) },
      options.signal,
    );
    const location = await this.deps.sink(asset);

    return [
      `Image generated and saved to ${location}.`,
      // Knowing WHERE the image is isn't the same as knowing how to use it: a
      // model told only "saved to X" tends to describe the picture in prose
      // instead of embedding it. Spelling out the reference syntax here makes
      // the worker's "never write a placeholder" rule concretely actionable,
      // and it works for every host because `location` is whatever that host's
      // sink returned — a workspace path on desktop/CLI, a URL in the cloud.
      `To include this image in your output, reference it as: ![description](${location})`,
      `Model: ${asset.modelId} — ${r.selected.reason}`,
      // DALL·E rewrites the prompt before drawing; the model needs to know what
      // was actually rendered, not what it asked for, or its description of the
      // result will not match the image.
      asset.revisedPrompt ? `The provider rewrote the prompt to: ${asset.revisedPrompt}` : '',
    ].filter(Boolean).join('\n');
  }
}

// ── Speech ────────────────────────────────────

export class GenerateSpeechTool extends BaseTool {
  readonly name = 'generate_speech';
  readonly description =
    'Turn text into spoken audio using the best available text-to-speech model. Returns where the audio was saved. Use when the user asks for narration, a voiceover or an audio version of some text.';
  readonly inputSchema = {
    type: 'object',
    properties: {
      text: { type: 'string', description: 'The text to speak.' },
      voice: { type: 'string', description: 'Voice id: alloy, echo, fable, onyx, nova, shimmer. Default alloy.' },
      format: { type: 'string', description: 'Audio format: mp3 (default), opus, aac, flac, wav.' },
      model: { type: 'string', description: 'Optional: force a specific speech model.' },
    },
    required: ['text'],
  };

  constructor(private deps: Deps) { super(); }

  async execute(input: Record<string, unknown>, options: ToolExecuteOptions): Promise<string> {
    const text = String(input['text'] ?? '').trim();
    if (!text) return 'Provide "text" to speak.';

    const r = resolve(this.deps, 'speech', input['model'] ? String(input['model']) : undefined);
    if (!r.ok) return r.error;

    const fmt = String(input['format'] ?? 'mp3');
    const allowed = ['mp3', 'opus', 'aac', 'flac', 'wav'] as const;
    const format = (allowed as readonly string[]).includes(fmt)
      ? fmt as typeof allowed[number]
      : 'mp3';

    const asset = await generateSpeech(
      r.selected.capability, r.cfg,
      { text, voice: input['voice'] ? String(input['voice']) : undefined, format },
      options.signal,
    );
    const location = await this.deps.sink(asset);
    return `Speech generated and saved to ${location}.\nModel: ${asset.modelId} — ${r.selected.reason}`;
  }
}

// ── Video ─────────────────────────────────────

/** Clip length used when the caller doesn't say. Kept short — see the cost note. */
const DEFAULT_VIDEO_SECONDS = 5;
/** Hard ceiling regardless of what the model asks for. */
const MAX_VIDEO_SECONDS = 8;

export class GenerateVideoTool extends BaseTool {
  readonly name = 'generate_video';
  // The price is in the description on purpose. Video is ~1000x the cost of an
  // image per call, it is billed per SECOND, and the model choosing the
  // duration is the one deciding the bill — so the number has to be where the
  // model reads before calling, not only in the result afterwards.
  readonly description =
    'Generate a short video clip from a text description. EXPENSIVE and slow: billed per second of output (about $0.40/second, so a 5-second clip costs roughly $2) and takes 1-3 minutes. Only use when the user explicitly asks for a video, and prefer the shortest duration that satisfies the request.';
  readonly inputSchema = {
    type: 'object',
    properties: {
      prompt: { type: 'string', description: 'What the video should show: subject, action, camera movement, style.' },
      seconds: { type: 'number', description: `Clip length, 1-${MAX_VIDEO_SECONDS} seconds (default ${DEFAULT_VIDEO_SECONDS}). Billed per second — keep it short.` },
      aspectRatio: { type: 'string', description: 'Frame shape: "16:9" (default) or "9:16" for vertical.' },
      model: { type: 'string', description: 'Optional: force a specific video model.' },
    },
    required: ['prompt'],
  };

  constructor(private deps: Deps) { super(); }

  async execute(input: Record<string, unknown>, options: ToolExecuteOptions): Promise<string> {
    const prompt = String(input['prompt'] ?? '').trim();
    if (!prompt) return 'Provide a "prompt" describing the video.';

    const r = resolve(this.deps, 'video', input['model'] ? String(input['model']) : undefined);
    if (!r.ok) return r.error;

    // Clamp rather than reject: a model asking for 30 seconds has misjudged the
    // cost, and silently spending $12 to teach it that would be the wrong
    // lesson to charge the user for.
    const asked = typeof input['seconds'] === 'number' ? input['seconds'] : DEFAULT_VIDEO_SECONDS;
    const seconds = Math.max(1, Math.min(MAX_VIDEO_SECONDS, Math.round(asked)));

    const asset = await generateVideo(
      r.selected.capability, r.cfg,
      {
        prompt,
        seconds,
        ...(input['aspectRatio'] ? { aspectRatio: String(input['aspectRatio']) } : {}),
      },
      options.signal,
      // Progress goes to the run log so a two-minute wait doesn't look like a
      // hang — the single most likely reason someone kills a working render.
      (note) => options.onProgress?.(note),
    );
    const location = await this.deps.sink(asset);

    const unit = r.selected.cost;
    const estimate = unit ? ` Estimated cost: $${(unit.amount * seconds).toFixed(2)} (${seconds}s x ${unit.label}).` : '';
    const clamped = seconds !== Math.round(asked) ? ` Duration was clamped to ${seconds}s (max ${MAX_VIDEO_SECONDS}).` : '';
    return `Video generated and saved to ${location}.\nModel: ${asset.modelId}.${estimate}${clamped}`;
  }
}

// ── Transcription ─────────────────────────────

export class TranscribeAudioTool extends BaseTool {
  readonly name = 'transcribe_audio';
  readonly description =
    'Transcribe a local audio file to text using the best available speech-to-text model. Use when the user supplies audio and wants its contents in writing.';
  readonly inputSchema = {
    type: 'object',
    properties: {
      path: { type: 'string', description: 'Path to the audio file to transcribe.' },
      language: { type: 'string', description: 'Optional ISO-639-1 language hint, e.g. "en", improves accuracy.' },
      model: { type: 'string', description: 'Optional: force a specific transcription model.' },
    },
    required: ['path'],
  };

  constructor(private deps: Deps, private readFile: (p: string) => Promise<Buffer>) { super(); }

  async execute(input: Record<string, unknown>, options: ToolExecuteOptions): Promise<string> {
    const filePath = String(input['path'] ?? '').trim();
    if (!filePath) return 'Provide a "path" to the audio file.';

    const r = resolve(this.deps, 'transcription', input['model'] ? String(input['model']) : undefined);
    if (!r.ok) return r.error;

    let audio: Buffer;
    try {
      audio = await this.readFile(filePath);
    } catch {
      return `Could not read the audio file at ${filePath}.`;
    }

    const { text, modelId } = await transcribeAudio(
      r.selected.capability, r.cfg,
      {
        audio,
        filename: filePath.split(/[\\/]/).pop() || 'audio',
        ...(input['language'] ? { language: String(input['language']) } : {}),
      },
      options.signal,
    );
    return text
      ? `Transcript (${modelId}):\n\n${text}`
      : `${modelId} returned an empty transcript — the file may be silent or in an unsupported format.`;
  }
}

/**
 * Build only the media tools this account can actually run.
 *
 * `transcribe_audio` additionally needs a file reader, so it is omitted on a
 * host with no filesystem (cloud) even when a transcription model exists —
 * there would be nothing for it to read.
 */
export function buildMediaTools(
  deps: Deps,
  readFile?: (p: string) => Promise<Buffer>,
): BaseTool[] {
  const tools: BaseTool[] = [];
  const modalities = new Set(deps.registry.availableModalities());
  if (modalities.has('image')) tools.push(new GenerateImageTool(deps));
  if (modalities.has('speech')) tools.push(new GenerateSpeechTool(deps));
  if (modalities.has('video')) tools.push(new GenerateVideoTool(deps));
  if (modalities.has('transcription') && readFile) tools.push(new TranscribeAudioTool(deps, readFile));
  return tools;
}
